#!/usr/bin/env bash
# Renders a Homebrew formula for a built release, with the real checksums of the
# archives that release actually published.
#
#   bash scripts/homebrew-formula.sh <release-dir> [formula-name]
#
# Two channels, chosen by the name you install rather than by configuration:
#
#   tula          stable — bumped only for a release promoted to it, so a build
#                 found to be wrong is skipped by simply not promoting the next
#   tula-latest   every release, including pre-releases
#
# The lag is worth more here than for a coding tool: a bad build does not fail
# loudly, it shows someone a wrong liquidation number.
set -euo pipefail

RELEASE=${1:?usage: homebrew-formula.sh <release-dir> [formula-name]}
NAME=${2:-tula}
VERSION=$(grep -m1 'APP_VERSION' src/version.ts | sed "s/.*'\([^']*\)'.*/\1/")
REPO_URL=$(grep -m1 'REPO_URL' src/version.ts | sed "s/.*'\([^']*\)'.*/\1/")
DESCRIPTION=$(grep -m1 'APP_DESCRIPTION' src/version.ts | sed "s/.*'\([^']*\)'.*/\1/")
SITE_URL=$(grep -m1 'SITE_URL' src/version.ts | sed "s/.*'\([^']*\)'.*/\1/")
BASE="$REPO_URL/releases/download/v$VERSION"

# tula -> Tula, tula-latest -> TulaLatest. Homebrew resolves the class from the
# file name by this rule, and a mismatch fails the tap for every user at once.
CLASS=$(printf '%s' "$NAME" | awk -F- '{for(i=1;i<=NF;i++) printf toupper(substr($i,1,1)) substr($i,2)}')

sum_for() {
  grep " tula-v$VERSION-$1.tar.gz\$" "$RELEASE/checksums.txt" | cut -d' ' -f1
}

# The stable channel is the one people get by typing the obvious thing, so it is
# the one that names the other. Conflicting is deliberate: two tula binaries on
# one PATH is a coin toss about which liquidation number you are reading.
OTHER=$([ "$NAME" = tula ] && echo tula-latest || echo tula)

cat <<FORMULA
# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class $CLASS < Formula
  desc "$DESCRIPTION"
  homepage "$SITE_URL"
  version "$VERSION"
  license "MIT"

  on_macos do
    on_arm do
      url "$BASE/tula-v$VERSION-darwin-arm64.tar.gz"
      sha256 "$(sum_for darwin-arm64)"
    end
    on_intel do
      url "$BASE/tula-v$VERSION-darwin-x64.tar.gz"
      sha256 "$(sum_for darwin-x64)"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/tula-v$VERSION-linux-arm64.tar.gz"
      sha256 "$(sum_for linux-arm64)"
    end
    on_intel do
      url "$BASE/tula-v$VERSION-linux-x64.tar.gz"
      sha256 "$(sum_for linux-x64)"
    end
  end

  conflicts_with "$OTHER", because: "both install a tula binary"

  def install
    bin.install "tula"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tula --version")
    # Read-only is the product, so the test asserts the refusal, not just that
    # the binary starts: a build that grew a way to move money must not ship.
    assert_match "places no order", shell_output("#{bin}/tula about")
  end
end
FORMULA
