#!/usr/bin/env bash
# Renders a Homebrew formula for a built release, with the real checksums of the
# archives that release actually published.
#
#   bash scripts/homebrew-formula.sh <release-dir> [formula-name]
#
# Three names, and which one you install is the whole of the choice:
#
#   tula            stable — bumped only for a release promoted to it, so a build
#                   found to be wrong is skipped by simply not promoting the next
#   tula-latest     every release, including pre-releases
#   tula@<version>  that release and no other, kept for as long as the tap is
#
# The lag is worth more here than for a coding tool: a bad build does not fail
# loudly, it shows someone a wrong liquidation number. The pinned name exists for
# the same reason in the other direction — a formula holds one version, so
# without a file per release the way back to a known-good build is gone the
# moment the next one is published, and Homebrew is the only channel where that
# is true: the installer takes TULA_VERSION and npm takes @<version>.
set -euo pipefail

RELEASE=${1:?usage: homebrew-formula.sh <release-dir> [formula-name]}
NAME=${2:-tula}
VERSION=$(grep -m1 'APP_VERSION' src/version.ts | sed "s/.*'\([^']*\)'.*/\1/")
REPO_URL=$(grep -m1 'REPO_URL' src/version.ts | sed "s/.*'\([^']*\)'.*/\1/")
DESCRIPTION=$(grep -m1 'APP_DESCRIPTION' src/version.ts | sed "s/.*'\([^']*\)'.*/\1/")
SITE_URL=$(grep -m1 'SITE_URL' src/version.ts | sed "s/.*'\([^']*\)'.*/\1/")
BASE="$REPO_URL/releases/download/v$VERSION"

# Homebrew's Formulary.class_s, which is what resolves a file name to the class
# it must declare: capitalize, fold `-`, `_`, `.` and space into an upcased next
# character, `+` to `x`, then `@` to `AT`. Mirrored rather than special-cased for
# the names we happen to ship, because `tula@0.1.0` must say `TulaAT010` and a
# rule written for `tula-latest` alone silently produces `Tula@0.1.0` — a
# mismatch fails the whole tap for every user at once, not just the new formula.
CLASS=$(printf '%s' "$NAME" | awk '{
  out = ""; up = 1
  for (i = 1; i <= length($0); i++) {
    c = substr($0, i, 1)
    if (c ~ /[-_. ]/) { up = 1; continue }
    if (c == "+") { out = out "x"; up = 0; continue }
    out = out (up ? toupper(c) : c); up = 0
  }
  sub(/@/, "AT", out)
  print out
}')

die() { echo "homebrew-formula: $1" >&2; exit 1; }

sum_for() {
  grep " tula-v$VERSION-$1.tar.gz\$" "$RELEASE/checksums.txt" | cut -d' ' -f1
}

# Resolved before the heredoc, and each one checked. `set -e` does not fire for
# a command substitution inside a heredoc, so a checksums.txt missing a target
# rendered a valid formula carrying `sha256 ""` and exited 0 — which the release
# job then commits and pushes, and every `brew install` on that platform fails
# as a checksum mismatch, after the GitHub release is already public.
SUM_DARWIN_ARM64=$(sum_for darwin-arm64)
SUM_DARWIN_X64=$(sum_for darwin-x64)
SUM_LINUX_ARM64=$(sum_for linux-arm64)
SUM_LINUX_X64=$(sum_for linux-x64)
for t in darwin-arm64 darwin-x64 linux-arm64 linux-x64; do
  var=SUM_$(printf '%s' "$t" | tr 'a-z-' 'A-Z_')
  [ -n "${!var}" ] || die "no checksum for tula-v$VERSION-$t.tar.gz in $RELEASE/checksums.txt"
done

# Two tula binaries on one PATH is a coin toss about which liquidation number you
# are reading, and the two channels and the pinned versions refuse that in the
# two ways Homebrew offers. The channels conflict, because they are alternatives
# and picking one is the point. A pinned version is keg_only instead: it cannot
# name every other pinned version, those files do not exist yet when this one is
# rendered — and keg_only is the stronger answer anyway, since an old build ends
# up on PATH only when somebody links it on purpose.
case "$NAME" in
  *@*) PATH_RULE="  keg_only :versioned_formula" ;;
  *) OTHER=$([ "$NAME" = tula ] && echo tula-latest || echo tula)
     PATH_RULE="  conflicts_with \"$OTHER\", because: \"both install a tula binary\"" ;;
esac

cat <<FORMULA
# Generated by scripts/homebrew-formula.sh. Do not edit by hand.
class $CLASS < Formula
  desc "$DESCRIPTION"
  homepage "$SITE_URL"
  version "$VERSION"
  license "MIT"

  on_macos do
    on_arm do
      url "$BASE/tula-v$VERSION-darwin-arm64.tar.gz"
      sha256 "$SUM_DARWIN_ARM64"
    end
    on_intel do
      url "$BASE/tula-v$VERSION-darwin-x64.tar.gz"
      sha256 "$SUM_DARWIN_X64"
    end
  end

  on_linux do
    on_arm do
      url "$BASE/tula-v$VERSION-linux-arm64.tar.gz"
      sha256 "$SUM_LINUX_ARM64"
    end
    on_intel do
      url "$BASE/tula-v$VERSION-linux-x64.tar.gz"
      sha256 "$SUM_LINUX_X64"
    end
  end

$PATH_RULE

  def install
    bin.install "tula"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tula --version")
    # Read-only is the product, so the test asserts the refusal, not just that
    # the binary starts: a build that grew a way to move money must not ship.
    assert_match "places no order", shell_output("#{bin}/tula about")
  end
end
FORMULA
