import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { keysJson, keysMarkdown } from '../src/ui/keymap.js'

/**
 * Writes the keys reference wherever it is published, from `src/ui/keymap.ts`:
 * the section `README.md` holds between its markers, and the data the site's
 * keys page renders. `--check` writes nothing and exits 1 where either differs,
 * which `src/ui/keymap.test.ts` runs on every `bun test` — the shape of Gemini
 * CLI's `generate-keybindings-doc.ts`, whose check a test runs the same way.
 *
 *   bun run keys:docs
 *   bun run keys:docs --check
 */

export const START = '<!-- keys:start — generated by `bun run keys:docs` from src/ui/keymap.ts; edit the keymap, not this -->'
export const END = '<!-- keys:end -->'

export const README = 'README.md'
export const SITE_DATA = 'site/lib/keys.json'

const fromRoot = (path: string): string => join(import.meta.dir, '..', path)

/** Each published copy, as it is and as the keymap renders it. */
export function keysDocs(): { path: string; now: string; want: string }[] {
  const readme = readFileSync(fromRoot(README), 'utf8')
  const from = readme.indexOf(START)
  const to = readme.indexOf(END)
  if (from === -1 || to < from) {
    throw new Error(`${README} has no ${START} … ${END} section for the keys reference to go in`)
  }
  const section = `${START}\n\n${keysMarkdown()}\n\n`
  const wantReadme = readme.slice(0, from) + section + readme.slice(to)
  let site = ''
  try {
    site = readFileSync(fromRoot(SITE_DATA), 'utf8')
  } catch {
    // Not written yet: the check reports it as out of date, which it is.
  }
  return [
    { path: README, now: readme, want: wantReadme },
    { path: SITE_DATA, now: site, want: keysJson() },
  ]
}

if (import.meta.main) {
  const check = process.argv.includes('--check')
  const stale = keysDocs().filter((doc) => doc.now !== doc.want)
  if (check) {
    for (const doc of stale) console.error(`${doc.path} is out of date with src/ui/keymap.ts. Run: bun run keys:docs`)
    process.exitCode = stale.length > 0 ? 1 : 0
  } else {
    for (const doc of stale) writeFileSync(fromRoot(doc.path), doc.want)
    console.log(stale.length > 0 ? `Wrote ${stale.map((d) => d.path).join(', ')}` : 'Already current')
  }
}
